name: Rust

on:
  push:
    branches: [ "main", "doggy-dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: cargo build --release --verbose
      
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: cow
        path: target/release/cow.exe
